presets:
  global:
    download: /home/hara/flexget_torrents/torrent

  tv:
    series:
      - south park
      - The Big Bang Theory
      - californication
      - family guy
      - Futurama
      - MythBusters
      - Doctor Who
      - Californication

  en-movies:
    imdb:
      min_score: 7.1
      min_votes: 6000
      min_year: 2007
      reject_genres:
        - horror
        - documentary
        - musical
        - music
        - biography
    quality: dvdrip+ <=720p
    content_filter:
      reject:
        - '*.rar'
    regexp:
      reject:
        - \bTS\b: {from: title}
        - \bR5\b: {from: title}
        - \bMD\b: {from: title}
        - \bNL\b: {from: title}
    seen_movies: loose


tasks:

  ezrss:
    rss: http://ezrss.it/feed/
    preset: tv

  showrss:
    rss: http://showrss.karmorra.info/feeds/all.rss
    preset: tv

  torlock:
    rss: http://www.torlock.com/movies/rss.xml
    preset: en-movies
    movie_queue: yes

  TV_KickAssTorrents:
    rss: http://www.kickasstorrents.com/tv/2/?field=time_add&sorder=desc&rss=1
    preset: tv
    priority: 20
# ============================================================================
#
# 
# Lookit:
# http://flexget.com/wiki/Cookbook/UserAtlanta800
# http://flexget.com/wiki/Cookbook/Userhyper_ch
# http://flexget.com/wiki/Cookbook/Userfoulou
# https://github.com/gray/dotfiles/blob/master/.flexget/config.yml

# presets:
  # global:
    # download: /home/hara/flexget_torrents/torrent
  # premieres:
    # thetvdb_lookup: yes
# # require_field: series_genres
    # regexp:
      # reject:
        # - documentary: {from: series_genres}
    # series_premiere: yes
  # IMDB:
    # imdb:
      # min_score: 3.1
      # min_votes: 1000
      # reject_genres:
        # - biography
        # - documentary
        # - game-show
        # - history
        # - music
        # - new
        # - reality-tv
        # - romance
        # - sport
        # - talk-show
  # TV_Series:
    # import_series:
      # settings:
        # upgrade: yes
      # from:
        # text:
          # url: http://next-episode.net/PAGES/misc/export_calendar?z&u=harleypig&k=f5978573acadacdc2d12611096045488.ics
          # entry:
            # title: ^SUMMARY:(.*) - [0-9]+x[0-9]+.*$
            # url: ^SUMMARY:(.*) - [0-9]+x[0-9]+.*$
# TV_BTCHAT:
# rss: http://rss.bt-chat.com/?cat=9
# preset: TV_Series
# priority: 40
  # Premieres_BTCHAT:
    # rss: http://rss.bt-chat.com/?cat=9
    # preset: premieres
    # priority: 40
# # TV_TorrentDay:
# # rss: http://www.torrentday.com/get_rss.php?feed=direct&user=harleypig&cat=22,2,14,7&passkey=dfa1b3706146b096df8dbb9069ca41a4
# # preset: TV_Series
# # priority: 45
  # Premieres_TorrentDay:
    # rss: http://www.torrentday.com/get_rss.php?feed=direct&user=harleypig&cat=22,2,14,7&passkey=dfa1b3706146b096df8dbb9069ca41a4
    # preset: premieres
    # priority: 45
# # TV_TorrentReactor:
# # rss: http://www.torrentreactor.net/rss/rss_8.xml
# # preset: TV_Series
# # priority: 50
  # Premieres_TorrentReactor:
    # rss: http://www.torrentreactor.net/rss/rss_8.xml
    # preset: premieres
    # priority: 50
# # Mini_Series_Sceper:
# # scenereleases: http://sceper.eu/category/tv-shows/mini-series?themedemo=SceneRLSv3
# # accept_all: yes
# # priority: 55
# # Movies_RlsLog_DVDRip:
# # rlslog: http://www.rlslog.net/category/movies/dvdrip
# # accept_all: yes
# # preset: IMDB
# # priority: 60
# # Movies_RlsLog_DVDScr:
# # rlslog: http://www.rlslog.net/category/movies/dvdscr
# # accept_all: yes
# # preset: IMDB
# # priority: 65
# # EBook_RlsLog:
# # rlslog: http://www.rlslog.net/category/ebook/ebook
# # accept_all: yes
# # priority: 70
